// Database type definitions
// This file will be auto-generated by Supabase CLI
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  // Supabase database schema types will be generated here
}
