openapi: 3.0.3
info:
  title: Volvox.Sober Authentication API
  description: User authentication endpoints (signup, login, password reset) using Supabase Auth
  version: 1.0.0
  contact:
    name: Volvox.Sober API Support

servers:
  - url: https://{project-id}.supabase.co/auth/v1
    description: Supabase Auth endpoint
    variables:
      project-id:
        default: your-project-id
        description: Supabase project identifier

paths:
  /signup:
    post:
      summary: Create new user account
      description: Register a new user with email and password. Sends verification email.
      operationId: signup
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - role
                - name
                - age
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  minLength: 6
                  example: securePass123
                role:
                  type: string
                  enum: [sponsor, sponsee, both]
                  description: User's primary role
                  example: sponsee
                name:
                  type: string
                  minLength: 2
                  maxLength: 100
                  example: John Doe
                age:
                  type: integer
                  minimum: 13
                  example: 28
                gender:
                  type: string
                  maxLength: 50
                  example: Male
                location_city:
                  type: string
                  maxLength: 100
                  example: San Francisco
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '400':
          description: Invalid request (email format, weak password, missing fields)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: User already registered

  /token:
    post:
      summary: Login with email and password
      description: Authenticate user and return JWT session token
      operationId: login
      tags:
        - Authentication
      parameters:
        - in: query
          name: grant_type
          required: true
          schema:
            type: string
            enum: [password]
          description: OAuth2 grant type (always 'password' for email/password)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: securePass123
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Invalid login credentials

  /recover:
    post:
      summary: Request password reset email
      description: Send password reset link to user's email address
      operationId: requestPasswordReset
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
      responses:
        '200':
          description: Reset email sent (always returns 200 even if email doesn't exist for security)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password reset email sent
        '429':
          description: Too many requests (rate limited)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user:
    get:
      summary: Get current user
      description: Retrieve authenticated user's profile
      operationId: getCurrentUser
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized (invalid or expired token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update user profile
      description: Update authenticated user's profile information
      operationId: updateUser
      tags:
        - Authentication
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 100
                age:
                  type: integer
                  minimum: 13
                gender:
                  type: string
                  maxLength: 50
                location_city:
                  type: string
                  maxLength: 100
                bio:
                  type: string
                  maxLength: 1000
                theme_preference:
                  type: string
                  enum: [light, dark, system]
                fcm_token:
                  type: string
                  description: Firebase Cloud Messaging token for push notifications
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /logout:
    post:
      summary: Logout user
      description: Invalidate current session token
      operationId: logout
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Logout successful (no content)
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Supabase JWT token obtained from login

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000
        email:
          type: string
          format: email
          example: user@example.com
        email_verified:
          type: boolean
          example: true
        role:
          type: string
          enum: [sponsor, sponsee, both]
          example: sponsee
        name:
          type: string
          example: John Doe
        age:
          type: integer
          example: 28
        gender:
          type: string
          example: Male
        location_city:
          type: string
          example: San Francisco
        bio:
          type: string
          example: Two years sober, looking for support
        profile_photo_url:
          type: string
          format: uri
          nullable: true
        theme_preference:
          type: string
          enum: [light, dark, system]
          example: system
        account_status:
          type: string
          enum: [active, on_hiatus, suspended]
          example: active
        created_at:
          type: string
          format: date-time
          example: '2025-01-15T10:30:00Z'
        updated_at:
          type: string
          format: date-time
          example: '2025-01-20T14:45:00Z'

    Session:
      type: object
      properties:
        access_token:
          type: string
          description: JWT access token
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        token_type:
          type: string
          example: bearer
        expires_in:
          type: integer
          description: Token expiration time in seconds
          example: 3600
        refresh_token:
          type: string
          description: Token for refreshing the session
          example: v1.MR5twH5UWJldXMYKRg...
        user:
          $ref: '#/components/schemas/User'

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Invalid request
        error_description:
          type: string
          description: Detailed error explanation
          example: Email format is invalid
        status_code:
          type: integer
          example: 400
