openapi: 3.0.0
info:
  title: Matches API
  version: 1.0.0

paths:
  /matches:
    get:
      summary: Get suggested matches
      operationId: getMatches
      parameters:
        - name: program
          in: query
          schema:
            type: string
        - name: availability
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Matches retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'

  /matches/{id}:
    get:
      summary: Get match profile details
      operationId: getMatchProfile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Match profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchProfile'

  /matches/{id}/request:
    post:
      summary: Send connection request
      operationId: sendConnectionRequest
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: Connection request sent
        '429':
          description: Rate limit exceeded (5 per day)

  /matches/{id}/decline:
    post:
      summary: Decline match (30-day cooldown)
      operationId: declineMatch
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Match declined

components:
  schemas:
    Match:
      type: object
      properties:
        id:
          type: string
          format: uuid
        candidate_id:
          type: string
          format: uuid
        compatibility_score:
          type: integer
          minimum: 0
          maximum: 100
        candidate_name:
          type: string
        candidate_bio:
          type: string
        recovery_program:
          type: string
        sobriety_days:
          type: integer
        location:
          type: string

    MatchProfile:
      allOf:
        - $ref: './profiles.yaml#/components/schemas/Profile'
        - type: object
          properties:
            compatibility_score:
              type: integer
