openapi: 3.0.0
info:
  title: Messages API
  version: 1.0.0
  description: Real-time messaging via REST + Supabase Realtime

paths:
  /messages/threads:
    get:
      summary: Get all message threads
      operationId: getMessageThreads
      responses:
        '200':
          description: Message threads retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MessageThread'

  /messages/threads/{id}:
    get:
      summary: Get messages in thread
      operationId: getThreadMessages
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
        - name: before
          in: query
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Messages retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
                  has_more:
                    type: boolean

  /messages/threads/{id}/send:
    post:
      summary: Send message in thread
      operationId: sendMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
                  minLength: 1
                  maxLength: 5000
      responses:
        '201':
          description: Message sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Invalid message content
        '429':
          description: Rate limit exceeded (100 per hour)

  /messages/{id}/read:
    patch:
      summary: Mark message as read
      operationId: markMessageRead
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Message marked as read

  /messages/subscribe:
    get:
      summary: Subscribe to real-time messages (Supabase Realtime)
      operationId: subscribeToMessages
      description: |
        WebSocket subscription via Supabase Realtime Broadcast.
        Client should use Supabase JS SDK to subscribe:

        ```typescript
        const channel = supabase
          .channel(`connection:${connectionId}`, { config: { private: true } })
          .on('broadcast', { event: 'new_message' }, (payload) => {
            handleNewMessage(payload.payload);
          })
          .subscribe();
        ```
      responses:
        '101':
          description: WebSocket connection established

components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
        connection_id:
          type: string
          format: uuid
        sender_id:
          type: string
          format: uuid
        text:
          type: string
        status:
          type: string
          enum: [sending, sent, delivered, read]
        created_at:
          type: string
          format: date-time
        delivered_at:
          type: string
          format: date-time
          nullable: true
        read_at:
          type: string
          format: date-time
          nullable: true
        sender:
          $ref: '#/components/schemas/MessageSender'

    MessageSender:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        profile_photo_url:
          type: string
          nullable: true

    MessageThread:
      type: object
      properties:
        connection_id:
          type: string
          format: uuid
        other_user:
          $ref: './connections.yaml#/components/schemas/ConnectionUser'
        last_message:
          $ref: '#/components/schemas/Message'
        unread_count:
          type: integer
