openapi: 3.0.0
info:
  title: Profiles API
  version: 1.0.0
  description: User profile CRUD operations via Supabase

paths:
  /profiles/{id}:
    get:
      summary: Get user profile
      operationId: getProfile
      tags: [Profiles]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '404':
          description: Profile not found
        '403':
          description: Not authorized to view this profile

    patch:
      summary: Update user profile
      operationId: updateProfile
      tags: [Profiles]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdate'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '403':
          description: Not authorized to update this profile
        '422':
          description: Validation error

  /profiles/{id}/completion:
    get:
      summary: Get profile completion percentage
      operationId: getProfileCompletion
      tags: [Profiles]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Completion percentage retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  completion_percentage:
                    type: integer
                    minimum: 0
                    maximum: 100
                  missing_fields:
                    type: array
                    items:
                      type: string

components:
  schemas:
    Profile:
      type: object
      required: [id, name, role, recovery_program]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 100
        bio:
          type: string
          nullable: true
        profile_photo_url:
          type: string
          format: uri
          nullable: true
        role:
          type: string
          enum: [sponsor, sponsee, both]
        recovery_program:
          type: string
          enum: [AA, NA, CA, Smart Recovery, Refuge Recovery, Secular, Other]
        sobriety_start_date:
          type: string
          format: date
          nullable: true
        city:
          type: string
          nullable: true
        state:
          type: string
          nullable: true
        country:
          type: string
          default: United States
        availability:
          type: array
          items:
            type: string
            enum: [weekdays, weekends, mornings, afternoons, evenings, anytime]
        preferences:
          type: object
          additionalProperties: true
        profile_completion_percentage:
          type: integer
          minimum: 0
          maximum: 100
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ProfileUpdate:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
        bio:
          type: string
        role:
          type: string
          enum: [sponsor, sponsee, both]
        recovery_program:
          type: string
        sobriety_start_date:
          type: string
          format: date
        city:
          type: string
        state:
          type: string
        availability:
          type: array
          items:
            type: string
        preferences:
          type: object
          additionalProperties: true
