openapi: 3.0.0
info:
  title: Sobriety Tracking API
  version: 1.0.0

paths:
  /sobriety/record:
    get:
      summary: Get sobriety record
      operationId: getSobrietyRecord
      responses:
        '200':
          description: Sobriety record retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SobrietyRecord'

  /sobriety/date:
    post:
      summary: Set sobriety start date
      operationId: setSobrietyDate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [start_date]
              properties:
                start_date:
                  type: string
                  format: date
      responses:
        '200':
          description: Start date updated

  /sobriety/reflection:
    post:
      summary: Add daily reflection
      operationId: addReflection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
                  maxLength: 1000
                date:
                  type: string
                  format: date
      responses:
        '201':
          description: Reflection added

  /sobriety/milestones:
    get:
      summary: Get milestone history
      operationId: getMilestones
      responses:
        '200':
          description: Milestones retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Milestone'

components:
  schemas:
    SobrietyRecord:
      type: object
      properties:
        current_sobriety_start_date:
          type: string
          format: date
        days_sober:
          type: integer
        milestones:
          type: array
          items:
            $ref: '#/components/schemas/Milestone'
        reflections:
          type: array
          items:
            $ref: '#/components/schemas/Reflection'

    Milestone:
      type: object
      properties:
        days:
          type: integer
        achieved_at:
          type: string
          format: date-time

    Reflection:
      type: object
      properties:
        date:
          type: string
          format: date
        text:
          type: string
